# Generated by Django 4.1.7 on 2024-03-18 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarWash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20)),
                (
                    "subcription_packages",
                    models.CharField(
                        choices=[
                            ("BP", "BASIC PACKAGE"),
                            ("PP", "PRESIDENTIAL PACKAGE"),
                            ("EP", "EXECUTIVE PACKAGE"),
                            ("EDP", "EXPRESS DETAILING PACKAGE"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "subcription_duration_in_month",
                    models.CharField(
                        choices=[
                            ("1MNT", "1-MONTH"),
                            ("2MNT", "3-MONTH"),
                            ("6MNT", "6-MONTH"),
                            ("12MNT", "12-MONTH"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("times_of_wash", models.IntegerField()),
                ("number_0f_cars", models.IntegerField()),
                ("package_price", models.IntegerField()),
                ("reward_points", models.IntegerField()),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carwash",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
